config/routes.rb
  get 'delivery_users/:id/store_index' => "delivery_users#store_index"
  post 'delivery_users/:id/store_save' => "delivery_users#store_save"

  get 'activities/skipe_one_index/:id/:platform' => 'activities#skipe_one_index'
  get 'activities/skipe_one_search'
  get 'activities/full_reduction/:userinfo_id/:full_reduction_id/:platform' => 'activities#fullReductions'
  get 'activities/promotion_discount/:userinfo_id/:promotion_discount_id/:platform' => 'activities#promotionDiscount'
  get 'activities/coupons/:userinfo_id/:platform' => 'activities#coupons'
  get 'activities/promotions/:userinfo_id/:platform' => 'activities#promotions'
  get 'activities/discount/:userinfo_id/:platform' => 'activities#discount'

  resources :coupons do
    get :invalided
    get 'products/:product_id/:operat' => :products, :on => :collection
    get :selectProducts, :on => :collection
  end
  resources :carous do
    get 'downloadS', :on => :collection
  end

  resources :full_reductions do
    get 'products/:product_id/:operat' => :products, :on => :collection
    get 'coupons/:coupon_info/:operat' => :coupons, :on => :collection
    get 'giftProducts/:product_info/:operat' => :giftProducts, :on => :collection
  end

  resources :panic_buyings do
    get 'product_list', :on => :collection
    get 'product'
    get 'panic_table', :on => :collection

    post 'add_product'
    get 'remove_product'
  end

  resources :carousels do
    post 'upload'
    delete 'destroyAsset'
    get 'downloadAsset'
  end

  mount RuCaptcha::Engine => "/rucaptcha"
  resources :userinfos do
    get 'jyd_index', :on => :collection
    get 'jyd_new', :on => :collection
    post 'jyd_create', :on => :collection
    get 'jyd_show/:userinfo_id', to: "userinfos#jyd_show", :on => :collection
    get 'jyd_edit/:userinfo_id', to: "userinfos#jyd_edit", :on => :collection
    patch 'jyd_update/:userinfo_id', to: "userinfos#jyd_update", :on => :collection
    post 'jyd_check/:userinfo_id', to: "userinfos#jyd_check", :on => :collection
    post 'jyd_check_out/:userinfo_id', to: "userinfos#jyd_check_out", :on => :collection
    delete 'jyd_destroy/:userinfo_id', to: "userinfos#jyd_destroy", :on => :collection

    get 'audit', :on => :collection
    get 'email_active/:confirmation_token', :action => :email_active, :on => :collection

    post 'userinfo_edit'

    resources :products do
      get 'desc'
      get 'preview'
    end
  end

  get "/user_mailer/signup_confirmation", :as => "user_mailer"

  resources :statistics do
    post 'search', :on => :collection
  end
  resources :cashiers do
    post 'checkCustomer', :on => :collection
  end

  resources :orders do
    resources :ordergoods
    post 'line_order_creat', :on => :collection
    get 'distribution_completed'
    get 'receive_order'

    get 'order_state_count', :on => :collection
    get 'orders_table_data', :on => :collection

    get 'statistic', :on => :collection
    get 'statisticData', :on => :collection
    post "wx_notify", :on => :member
    post "alipay_notify", :on => :member
    post "alipay_refund_notify", :on => :member
    post "alipay_dback_notify", :on => :member
    get 'line_payment_order', :on => :collection
  end

  resources :userinfo_orders do
    post 'binduserinfo', :on => :collection
    get 'getcode', :on => :collection
    get 'bind_form', :on => :collection
  end

  resources :announcements do
    get 'check'
    get 'check_out'
    post 'batch', :on => :collection
    get 'app_show'

    get 'warehouse_notice_index', :on => :collection
    get 'batch_check', :on => :collection
    get 'next_check', :on => :collection
    get 'next_check_out', :on => :collection
    get 'next_delete', :on => :collection
    post 'stow', :on => :collection
    post 'batch_delete', :on => :collection
    post 'announcement_hit'
  end

  resources :announcement_categories

  resources :pictures do
    post 'upload'
  end

  resources :categories

  devise_for :users, controllers: {
                       sessions: 'users/sessions',
                       registrations: 'users/registrations', #-----addby <dfj>
                   }

  devise_scope :user do
    get "users/sessions/password_reset", to: "users/sessions#password_reset"
    get "users/sessions/cheak_mobile", to: "users/sessions#cheak_mobile"
    get "users/send_message", to: "users/registrations#send_message"
    post "users/sessions/fix_password", to: "users/sessions#fix_password"
    post "users/mobile_sign_in", to: "users/mobile_sessions#create"
    post "users/mobile_sign_out", to: "users/mobile_sessions#destroy"
  end

  root to: "root#index"

  mount ElephantV1Api => '/api/v1/'

  mount ResqueWeb::Engine => "/resque"

  namespace :api do
    namespace :v1 do

      get 'products/find/:qrcode' => 'product#find'

      post 'user/register' => 'registrations#create'

      resources :products

    end
  end

  resources :products do

    get 'category_index', :on => :collection

    get 'demo', :on => :collection

    get 'demo_stress', :on => :collection

    post 'search', :on => :collection

    post 'searchByQrcode', :on => :collection

    get 'dataTablesProducts', :on => :collection

    post 'upload'

    post 'rack'

    get 'state'

    get 'page/:page', :action => :index, :on => :collection

    get 'warehouse_index', :on => :collection

    get 'statistic', :on => :collection
    get 'statisticData', :on => :collection

    get 'warehouse_show'
  end

  namespace :admin do
    post 'users/upload'
    resources :users
    post 'users/manage_store'
    get 'users/:id/reset_password' => 'users#reset_password'
    get 'users/:id/modify_loginpasswordForm' => 'users#modify_loginpasswordForm'
    post 'users/modify_loginpassword' => 'users#modify_loginpassword'
  end

  resources :mobile_categories

  resources :stores do
    get 'delivery_users'
    post 'add_delivery_user'
    post 'reduce_delivery_user'
    post 'upload'
    get 'search', :on => :collection
  end

  resources :chateaus do
    get 'turn_picture'
    post 'turn_picture_add'
    delete 'turn_picture_reduce'
    post 'turn_picture_urls'
    get 'introduce_show'
    get 'chateau_mark'
    post 'chateau_mark_add'
    delete 'chateau_mark_reduce'
    get 'check'
    get 'check_out'
    get 'search', :on => :collection
    get 'wines'
    get 'workload', :on => :collection
    post 'relate_wine'
    get 'resolve_wine'
    get 'ex_pic', :on => :collection
    get 'batch_check', :on => :collection
    get 'next_check', :on => :collection
    get 'next_check_out', :on => :collection
  end
  resources :chateau_marks

  resources :chateau_comments do
  end
  post 'chateau_comments/add_comment' => 'chateau_comments#add_comment'
  post 'chateau_comments/hit' => 'chateau_comments#hit'
  resources :regions do
    get 'children'
    post 'add_children'
    delete 'reduce_children'
    post 'get_children'
  end
  resources :wines do
    post 'table', :on => :collection
    get 'turn_picture'
    post 'turn_picture_add'
    delete 'turn_picture_reduce'
    post 'turn_picture_urls'
    get 'introduce_show'
    get 'mark'
    post 'mark_add'
    delete 'mark_reduce'
    get 'check'
    get 'check_out'
    get 'search', :on => :collection
    post 'picture_upload', :on => :collection
  end
  post 'ckeditor/pictures' => 'wines#upload'
  post 'phone_books/upload'
  get 'share_integrals/share' => 'share_integrals#share'

  resources :share_integrals do
    post 'register'
    post 'share_time_check', :on => :collection
    get 'share_integral_role'
    resources :share_integral_records

  end

  get 'dashboards/index' => 'dashboards#index'
  post 'dashboards/store_order_data' => "dashboards#store_order_data"
  post 'dashboards/exposure_product_data' => "dashboards#exposure_product_data"
  post 'dashboards/sale_product_data' => "dashboards#sale_product_data"
  get 'common/create_qrcode_image' => "common#create_qrcode_image"

  post 'jxc_stock_transfer_bills/audit'
  post 'jxc_stock_transfer_bills/strike_a_balance'
  post 'jxc_stock_transfer_bills/invalid'
  resources :jxc_stock_transfer_bills

  post 'jxc_stock_reduce_bills/audit'
  post 'jxc_stock_reduce_bills/strike_a_balance'
  post 'jxc_stock_reduce_bills/invalid'
  resources :jxc_stock_reduce_bills

  post 'jxc_stock_overflow_bills/audit'
  post 'jxc_stock_overflow_bills/strike_a_balance'
  post 'jxc_stock_overflow_bills/invalid'
  resources :jxc_stock_overflow_bills

  post 'jxc_stock_count_bills/audit_in_advance'
  post 'jxc_stock_count_bills/generate_pl_bill'
  post 'jxc_stock_count_bills/finally_confirm'
  post 'jxc_stock_count_bills/invalid'
  resources :jxc_stock_count_bills

  post 'jxc_stock_assign_bills/audit'
  post 'jxc_stock_assign_bills/strike_a_balance'
  post 'jxc_stock_assign_bills/invalid'
  resources :jxc_stock_assign_bills

  resources :jxc_sell_exchange_goods_bills

  post 'jxc_sell_returns_bills/audit'
  post 'jxc_sell_returns_bills/strike_a_balance'
  post 'jxc_sell_returns_bills/invalid'
  resources :jxc_sell_returns_bills

  post 'jxc_sell_stock_out_bills/audit'
  post 'jxc_sell_stock_out_bills/strike_a_balance'
  post 'jxc_sell_stock_out_bills/invalid'
  post 'jxc_sell_stock_out_bills/generate_sell_out_bill'
  resources :jxc_sell_stock_out_bills

  post 'jxc_sell_orders/audit'
  post 'jxc_sell_orders/strike_a_balance'
  post 'jxc_sell_orders/invalid'
  resources :jxc_sell_orders

  resources :jxc_purchase_exchange_goods_bills

  post 'jxc_purchase_returns_bills/audit'
  post 'jxc_purchase_returns_bills/strike_a_balance'
  post 'jxc_purchase_returns_bills/invalid'
  resources :jxc_purchase_returns_bills

  post 'jxc_purchase_stock_in_bills/audit'
  post 'jxc_purchase_stock_in_bills/strike_a_balance'
  post 'jxc_purchase_stock_in_bills/invalid'
  resources :jxc_purchase_stock_in_bills

  post 'jxc_purchase_orders/audit'
  post 'jxc_purchase_orders/strike_a_balance'
  post 'jxc_purchase_orders/invalid'
  resources :jxc_purchase_orders

  post 'jxc_other_stock_out_bills/audit'

app/models/announcement.rb
class Announcement
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Paperclip
  included Mongoid::Attributes::Dynamic

  belongs_to :user
  belongs_to :state
  belongs_to :announcement_category
  has_many :chateau_comments


  field :title, type: String #标题
  field :content, type: String #正文
  field :pic_path, type: Array, default: [] #图片路径
  field :release_time, type: String #第三方发布时间
  field :description, type: String #描述
  field :author, type: String #作者
  field :status, type: Integer, default: 0 #0：默认，1：审核通过，－1:审核不通过
  field :read_num, type: Integer, default: 0 #阅读量
  field :is_top, type: Integer, default: 0 #是否置顶,#0：默认，1：置顶，－1:不置顶
  field :reader, type: Array, default: [] #读者
  field :sequence, type: Integer, default: 0 #排序字段
  field :news_url, type: String #链接
  field :source, type: String #来源
  field :customer_ids, type: Array, default: [] #收藏用户
  field :pic_thumb_path, type: Array, default: [] #缩略图
  field :hits, type: Integer, default: 0 #点赞数

  has_mongoid_attached_file :avatar,
                            :default_url => '/missing.png'
  validates_attachment_content_type :avatar, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]


  def status_str
    if self.status == 1
      p '通过'
    elsif self.status == 0
      p '待审核'
    elsif self.status == -1
      p '不通过'
    end
  end


  def is_top_str
    if self.is_top == 0
      p '不置顶'
    else
      p '置顶'
    end
  end

  def created_time
    created_at.strftime("%Y%m%d%H%M%S")
  end
end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

app/views/announcements/_form.html.erb
<%= form_for @announcement, remote: true do |f| %>
    <% if @announcement.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@announcement.errors.count, "error") %> prohibited this announcement from being saved:</h2>

          <ul>
            <% @announcement.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <%= select_tag(:announcement_category_id, options_for_select(AnnouncementCategory.all.map { |c| [c.name, c.id] }),
                   :class => 'chosen-container chosen-container-multi', :style => 'width:100px', :name => "announcement[announcement_category_id]") %>

    <div class="field">
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </div>


    <div class="field">
      <%= f.label :description %><br>
      <%= f.text_field :description %>
    </div>

    <div class="field">
      <%= f.label :is_top %><br>
      <%= f.check_box :is_top %>
    </div>

    <div class="field">
      <%= f.label :content %><br>
      <%= f.text_area :content, :class => "tinymce", :rows => 40, :cols => 120 %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>

<% end %>



<% if params[:action]== "edit" %>
    <!--引入TinyMCE富文本编辑器-->
    <script type="text/javascript">
        $(function () {
            var category_id = "<%=@announcement.announcement_category.id.to_s%>";
            $("#announcement_category_id").val(category_id);
        });
    </script>
<% end %>

app/views/announcements/app_show.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
  <meta charset="utf-8"/>

  <meta name="viewport" content="width=device-width,
                                     initial-scale=1.0,
                                     maximum-scale=1.0,
                                     user-scalable=no">


  <!-- 新 Bootstrap 核心 CSS 文件 -->
  <link rel="stylesheet" href="../../css/bootstrap.min.css">

  <!-- 可选的Bootstrap主题文件（一般不用引入） -->
  <link rel="stylesheet" href="../../css/bootstrap-theme.min.css">

  <!-- jQuery文件。务必在bootstrap.min.js 之前引入 -->
  <script src="../../js/jquery.min.js"></script>

  <!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
  <script src="../../js/bootstrap.min.js"></script>
  <style type="text/css">
      .container {

          font-family: SimHei;
      }

      #head_title {
          font-size: 140%;
          font-weight: 200;
          color: #202020;
          margin-top: 20px;
      }

      #head_source {
          margin: 5px -10px 15px -10px;
          color: #505050;
      }

      #source {

          font-size: 70%;
          text-align: justify;
      }

      #created_at {

          font-size: 70%;
          text-align: right;
      }

      #content {
          font-size: 120%;
          color: #505050;
          text-align: left;
      }

  </style>

  <script>
      //      function add_comment() {
      //          $.ajax({
      //              type: "POST",
      //              url: "/chateau_comments/add_comment",
      //              data: {
      //                  content: $("#textarea_content").val(),
      //                  user_id: $("#input_user_id").val(),
      //      announcement_id: announcement_id
      //              },
      //              dataType: "json",
      //              success: function (data) {
      //                  alert(JSON.stringify(data));
      //                  location.reload();
      //              }
      //          });
      //      }
      //      ;
      //
      //      function hit(a) {
      //
      //          $.ajax({
      //              type: "POST",
      //              url: "/chateau_comments/hit",
      //              data: {
      //                  chateau_comment_id: $("#input_chateau_comment_id" + a).val()
      //              },
      //              dataType: "json",
      //              success: function (data) {
      //                  var hits = parseInt($("#input_chateau_comment_hits" + a).val()) + 1;
      //                  $("#p_hits" + a).html(hits + "");
      //                  $("#btn_hits" + a).attr("disabled", true);
      //              }
      //          });
      //
      //      }
      //      ;
      //
      //
      //      function stow() {
      //          var customer_id = $("#customer_id").val();
      //          var announcement_id = $("#announcement_id").val();
      //          $.ajax({
      //              type: "POST",
      //              url: "/announcements/stow",
      //              data: {announcement_id: announcement_id, customer_id: customer_id},
      //              dataType: "json",
      //              success: function (data) {
      //                  var stows = parseInt($("#p_stows").text()) + 1;
      //                  $("#p_stows" + a).html(stows + "");
      //                  $("#btn_stow" + a).attr("disabled", true);
      //              }
      //          });
      //
      //      }
      //      ;




      function announcement_hit() {
          var announcement_id = $("#announcement_id").val();

          $.ajax({
              type: "POST",
              url: '/announcements/'+announcement_id+'/announcement_hit',
              data: {announcement_id: announcement_id},
              dataType: "json",
              success: function () {
              }
          });

          var hits = parseInt($("#p_announcement_hits").text()) + 1;
          $("#support_image").attr("src", "../../images/announcements/support_red.png");
          $("#p_announcement_hits").html(hits + "");
          $("#a_support_image").removeAttr("onclick");

      };

  </script>

</head>
<body class="container">


<div class="row" id="head_title">
  <div class="col-xs-12">
    <%= @announcement.title %>
  </div>
  <!--title-->
</div>
<!--head_title-->


<div class="row" id="head_source">

  <div class="col-xs-6" id="source">
    <% if @announcement.source.present? %>
        <%= @announcement.source %>
    <% else %>
        小达快讯
    <% end %></div>
  <div class="col-xs-6" id="created_at">
    <%= @announcement.created_at.to_s[5, 11] %>
  </div>

</div>


<div class="row" id="content">
  <div class="col-xs-12">
    <%= markdown @announcement.content %>
  </div>
  <!--content-->
</div>
<!--row_content-->


<div class="row">
  <div class="col-xs-12" style="text-align: center;background-color: #c7eeff">
    <p style="display:inline;color: #b2b2b2;font-size: 80%;">本文来自网络，不代表酒运达的任何立场</p>
  </div>
  <!--content-->
</div>
<!--row_content-->

<div class="row">
  <div class="col-xs-12">
    <a id="a_support_image" onclick="announcement_hit();">
      <img src="../../images/announcements/support_gray.png" id="support_image" style="display:block;margin-left:auto;margin-right:auto;height: 30%;width: 30%;">
    </a>

    <div style="text-align: center;color: #b2b2b2;font-size: 80%;">
      共有<p id="p_announcement_hits" style="display:inline;"><%= @announcement.hits %></p>次点赞
    </div>
  </div>
  <!--content-->
</div>
<!--row_content-->


<input type="hidden" id="announcement_id" value="<%= @announcement.id %>">

</body>

</html>

app/views/announcements/edit.html.erb
<div class="page-header alert alert-info">
  <h1>快讯编辑</h1>
</div>

<%= render :partial => 'form', :locals => { :type => "edit" }  %>

<%= link_to 'Show', '', 'data-href' =>announcements_path(@announcement) %> |
<%= link_to 'Back', '', 'data-href' =>announcements_path("page" => cookies['current_page']) %>

app/views/announcements/index.html.erb
<div class="col-xs-12" style="">
  <div class="col-xs-5" style=""><h1>快讯管理 </h1></div>
  <div class="col-xs-7" style="">
    <%= paginate @announcements %>
  </div>
</div>



<div class="col-xs-12">


  <div class="col-xs-6" style="">
    <%= link_to '快讯主页', '', 'data-href' => announcements_path, :class => 'btn btn-primary btn-xs' %>
    <%= link_to '批量审核', '', 'data-href' => batch_check_announcements_path(:status => 0), :class => 'btn btn-pink btn-xs' %>
    <%= link_to '不通过重审', '', 'data-href' => batch_check_announcements_path(:status => -1), :class => 'btn btn-warning btn-xs' %>
    <%= link_to '通过重审', '', 'data-href' => batch_check_announcements_path(:status => 1), :class => 'btn btn-success btn-xs' %>
    <%= link_to '增加单个', '', 'data-href' => new_announcement_path, :class => 'btn btn-primary btn-xs' %>
  </div>


  <div class="col-xs-6">
    <form id="search-scope" class="form-inline" method="post" data-remote="true" action="/announcements" accept-charset="UTF-8">
      <div class="form-group">
        <label for="title">标题:</label>
        <input id="title" class="form-control">
      </div>
      <div class="form-group">
        <label for="status">状态:</label>
        <select id="status" class="form-control">
          <option value="" selected="selected">请选择</option>
          <option value="0">未审核</option>
          <option value="1">通过</option>
          <option value="-1">不通过</option>
        </select>
      </div>

      <div class="form-group">
        <label for="status">种类:</label>
        <%= select_tag(:announcement_category_id, options_for_select(AnnouncementCategory.all.map { |c| [c.name, c.id] }.insert(0, ["--请选择--", "0"])), :id => "category") %>
      </div>

      <a class="btn btn-primary btn-sm" href="javascript:search();">搜索</a>
    </form>

  </div>

</div>
<table class="table table-striped table-bordered table-hover">
  <thead>
  <tr>
    <th>选中</th>
    <th>标题</th>
    <th>来源</th>
    <th>当前状态</th>
    <th>种类</th>
    <th>阅读量</th>
    <th>是否置顶</th>
    <th>创建时间</th>
    <th>创建人</th>
    <th></th>
    <th>操作</th>
    <th></th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @announcements.each do |announcement| %>
      <tr class="odd gradeX" id="tr_<%=announcement.id%>">
        <td>
          <div class="checkbox">
            <label>
              <input type="checkbox" class="ace" name="form-field-checkbox" value="<%=announcement.id.to_s%>">
              <span class="lbl"></span>
            </label>
          </div>
        </td>
        <td><%= link_to announcement.title, announcement_app_show_path(announcement.id) %></td>
        <td><%= announcement.source %></td>
        <td id="statusstr">
          <% if announcement.status == 1 %>
              通过
          <% elsif announcement.status == 0 %>
              待审核
          <% else
               announcement.status == -1 %>
              不通过
          <% end %>
        </td>
        <td><%= announcement.announcement_category.name if announcement.announcement_category.present? %></td>
        <td><%= announcement.read_num %></td>
        <td><%= announcement.is_top %></td>
        <td><%= announcement.created_at.strftime('%Y-%m-%d %H:%M:%S').to_s %></td>
        <td><%= announcement.user.name if announcement.user.present? %></td>
        <td><%= link_to '详细', '', 'data-href' => announcement_path(announcement), :class => 'btn btn-xs btn-primary' %></td>
        <td><%= link_to '编辑', "##{edit_announcement_path(announcement)}", 'data-href' => edit_announcement_path(announcement), :class => 'btn btn-xs btn-info' %></td>
        <% if announcement.status ==0 || announcement.status ==-1 %>
            <td><%= link_to '审核通过', '', 'data-href' => announcement_check_path(:announcement_id => announcement.id), :class => 'btn btn-xs btn-pink' %></td>
        <% else %>
            <td><%= link_to '审核不通过', '', 'data-href' => announcement_check_out_path(:announcement_id => announcement.id), :class => 'btn btn-xs btn-warning' %></td>
        <% end %>
        <td><%= link_to '删除', announcement, :remote => true, method: :delete, data: {confirm: 'Are you sure?'},
                        :class => 'btn btn-xs btn-danger' %></td>
      </tr>
  <% end %>
  <tr class="">
    <td colspan="12">
      <button class="btn btn-minier btn-danger btn-sm" id="" onclick="batch_delete();">
        <i class="ace-icon fa fa-trash-o bigger-120 orange"></i>
        Delete
      </button>
    </td>
    <td>
     批量删除
    </td>
  </tr>
  </tbody>
</table>

<br>
<div id="container">
  <div style="text_align:center; float: left">
    <%= paginate @announcements %>
  </div>
  <div style="text_align:center; float: right">
    <p>批量添加</p>
    <%= form_tag({action: :batch}, remote: true, multipart: true) do %>
        <p>1:请选择种类：</p>
        <%= select_tag(:announcement_category_id, options_for_select(AnnouncementCategory.all.map { |c| [c.name, c.id] }),
                       :class => 'chosen-container chosen-container-multi', :style => 'width:100px') %>
        <p>2:请选择正确格式的EXCEL文件：</p>
        <%= file_field_tag 'excel_file', accept: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel', id: 'excel_file_id' %>
        <%= submit_tag('提交', onclick: 'return submit_form()') %>
    <% end %>
  </div>
</div>

<% cookies['current_page']=params[:page] %>

app/views/announcements/new.html.erb
<h1>新建快讯</h1>

<%= render 'form' %>

<%= link_to 'Back','', 'data-href' => announcements_path %>

app/views/announcements/show.html.erb
<div class="row">
  <div class="col-xs-12">

    <div class="row">
      <div class="col-xs-12 col-sm-6
      "style="padding: 1% 2%;
              font-size: 140%;
              line-height: 160%;
              border-top: 1px solid #d6d6d6;">
        <%= markdown @announcement.content %>
      </div>

      <div class="col-xs-12 col-sm-6 widget-container-col ui-sortable">
        <div class="widget-box widget-color-blue light-border ui-sortable-handle">

          <div class="widget-header widget-header-large">
            <h4 class="widget-title bigger lighter">基本信息</h4>
          </div>


          <div class="widget-body">
            <div class="widget-main">
              标题：<%=  @announcement.title %>
              <br>
              类别：<%=  @announcement.announcement_category.name %>
              <br>
              是否置顶：<%=  @announcement.is_top_str %>
              <br>
              排序字段：<%=  @announcement.sequence %>
              <br>
              来源：<%=  @announcement.source %>
              <br>
              创建时间：<%=  @announcement.created_at.to_s %>
              <br>
              最后修改时间：<%=  @announcement.updated_at.to_s %>
              <br>
              图片数量：<%=  @announcement.pic_path.count %>
              <br>
              压缩图片数量：<%=  @announcement.pic_thumb_path.count %>
              <br>
              上传人：<%=  @announcement.user.name if @announcement.user.present? %>
              <br>
              当前审核状态：<%=  @announcement.status_str %>
            </div>
          </div>
        </div>

        <div class="widget-box widget-color-blue light-border ui-sortable-handle">

          <div class="widget-header widget-header-large">
            <h4 class="widget-title bigger lighter">操作:</h4>
            当前状态：
            <%=@announcement.status_str%>
            最后修改时间：
            <%=  @announcement.updated_at.to_s %>
            <br>
          </div>


          <div class="widget-body">
            <div class="widget-main">
              <div class=""></div>
              <%= link_to '通过', '', 'data-href' => next_check_announcements_path(:announcement_id => @announcement.id, :status => @announcement.status), :class => 'btn btn-success btn-xs' %>
              |
              <%= link_to '驳回', '', 'data-href' => next_check_out_announcements_path(:announcement_id => @announcement.id, :status => @announcement.status), :class => 'btn btn-warning btn-xs' %>
              |
              <%= link_to '修改', '', 'data-href' => edit_announcement_path(@announcement), :class => 'btn btn-inverse btn-xs' %>
              |
              <%= link_to '删除', '', 'data-href' => next_delete_announcements_path(:announcement_id => @announcement.id, :status => @announcement.status), :class => 'btn btn-danger btn-xs' %>
              |
              <%= link_to '返回', '', 'data-href' => announcements_path("page" => cookies['current_page']), :class => 'btn btn-primary btn-xs' %>
            </div>
          </div>
        </div>


      </div>


    </div>
  </div>
</div>

app/views/announcements/warehouse_notice_index.html.erb
<%- model_class = Announcement %>
<p id="notice"><%= notice %></p>
<div class="page-header">
  <div style="text_align:center; float: left">
    <h1>公告板</h1>
  </div>
</div>

<div class="container">
  <table class="table table-hover">
    <% @notices.each do |notice| %>
        <tr>
          <td width="10%" class="center">
            <img src="/images/avatar.png" class="msg-photo" alt="Alex's Avatar" height="50" width="50px"/>
          </td>
          <td width="90%">
            <div>
												<span class="msg-body">
													<span class="msg-title">
														<h4><a target="_blank" href="<%= RestConfig::PRODUCT_SERVER %>notices/<%= notice.id %>/app_show"><%= notice.title %></a></h4>
													</span>
<br/>
													<span class="msg-time">
														<i class="ace-icon fa fa-clock-o"></i>
														<span>管理员 发表于 <%= time_ago_in_words notice.created_at %>前</span>
													</span>
												</span>
            </div>
          </td>
        </tr>
    <% end %>
  </table>
</div>