config/routes.rb
Rails.application.routes.draw do

  resources :phone_books
  resources :feedbacks
  resources :roles
  resources :card_bags do

  end
  resources :clients do
    get "on_off"
  end
  resources :jxc_bill_detail
  resources :jxc_entering_stocks do
    get "prev", :on => :collection
    get "next", :on => :collection
    get "audit"
  end
  resources :product_tickets do
    get 'customers_import'
    get 'get_customers'
    post 'customer_add'
    post 'customer_reduce'
    post 'build_card_bag'
    post 'share_time_check', :on => :collection
    get 'share'
    post 'register'
    resources :product_ticket_customer_inits, shallow: true
    get 'product_ticket_role'
  end

  get '/product_ticket_customer_inits/:id/remove' => "product_ticket_customer_inits#remove" #酒劵用户移除

  get '/product_tickets/:product_ticket_id/product_ticket_customer_inits/import_customer' => "product_ticket_customer_inits#import_customer" #酒劵用户导入

  resources :user_integrals
  resources :wines

  resources :userinfo_asks
  resources :cashes
  resources :import_bags do
    resources :import_bag_receivers, shallow: true
  end
  resources :promotion_discounts do
    get 'products/:product_id/:operat/:type' => :products, :on => :collection
  end

  post 'import_bags/:import_bag_id/import_bag_receivers/batch' => "import_bag_receivers#batch" #后台收礼人批量导入
  get 'import_bags/import_bag_receivers/down_templ' => "import_bag_receivers#down_templ" #后台收礼人批量导入down_templ
  get 'gift_bags/:import_bag_id/index' => "gift_bags#index" #后台导入礼包认领情况

  post 'import_bags/products/table/data/' => "import_bags#products_table_data"
  post 'import_bags/workflow/deal' => "import_bags#deal"
  get 'import_bags/workflow/deal_list' => "import_bags#deal_list"

  resources :delivery_users
  post 'delivery_users/datatable'=> "delivery_users#datatable"
  get 'delivery_users/:id/check' => "delivery_users#check"
  post 'delivery_users/:id/check_save' => "delivery_users#check_save"
  get 'delivery_users/:id/store_index' => "delivery_users#store_index"
  post 'delivery_users/:id/store_save' => "delivery_users#store_save"

  get 'activities/skipe_one_index/:id/:platform' => 'activities#skipe_one_index'
  get 'activities/skipe_one_search'
  get 'activities/full_reduction/:userinfo_id/:full_reduction_id/:platform' => 'activities#fullReductions'
  get 'activities/promotion_discount/:userinfo_id/:promotion_discount_id/:platform' => 'activities#promotionDiscount'
  get 'activities/coupons/:userinfo_id/:platform' => 'activities#coupons'
  get 'activities/promotions/:userinfo_id/:platform' => 'activities#promotions'
  get 'activities/discount/:userinfo_id/:platform' => 'activities#discount'

  resources :coupons do
    get :invalided
    get 'products/:product_id/:operat' => :products, :on => :collection
    get :selectProducts, :on => :collection
  end
  resources :carous do
    get 'downloadS', :on => :collection
  end

  resources :full_reductions do
    get 'products/:product_id/:operat' => :products, :on => :collection
    get 'coupons/:coupon_info/:operat' => :coupons, :on => :collection
    get 'giftProducts/:product_info/:operat' => :giftProducts, :on => :collection
  end

  resources :panic_buyings do
    get 'product_list', :on => :collection
    get 'product'
    get 'panic_table', :on => :collection

    post 'add_product'
    get 'remove_product'
  end

  resources :carousels do
    post 'upload'
    delete 'destroyAsset'
    get 'downloadAsset'
  end

  mount RuCaptcha::Engine => "/rucaptcha"
  resources :userinfos do
    get 'jyd_index', :on => :collection
    get 'jyd_new', :on => :collection
    post 'jyd_create', :on => :collection
    get 'jyd_show/:userinfo_id', to: "userinfos#jyd_show", :on => :collection
    get 'jyd_edit/:userinfo_id', to: "userinfos#jyd_edit", :on => :collection
    patch 'jyd_update/:userinfo_id', to: "userinfos#jyd_update", :on => :collection
    post 'jyd_check/:userinfo_id', to: "userinfos#jyd_check", :on => :collection
    post 'jyd_check_out/:userinfo_id', to: "userinfos#jyd_check_out", :on => :collection
    delete 'jyd_destroy/:userinfo_id', to: "userinfos#jyd_destroy", :on => :collection

    get 'audit', :on => :collection
    get 'email_active/:confirmation_token', :action => :email_active, :on => :collection

    post 'userinfo_edit'

    resources :products do
      get 'desc'
      get 'preview'
    end
  end

  get "/user_mailer/signup_confirmation", :as => "user_mailer"

  resources :statistics do
    post 'search', :on => :collection
  end
  resources :cashiers do
    post 'checkCustomer', :on => :collection
  end

  resources :orders do
    resources :ordergoods
    post 'line_order_creat', :on => :collection
    get 'distribution_completed'
    get 'receive_order'

    get 'order_state_count', :on => :collection
    get 'orders_table_data', :on => :collection

    get 'statistic', :on => :collection
    get 'statisticData', :on => :collection
    post "wx_notify", :on => :member
    post "alipay_notify", :on => :member
    post "alipay_refund_notify", :on => :member
    post "alipay_dback_notify", :on => :member
    get 'line_payment_order', :on => :collection
  end

  resources :userinfo_orders do
    post 'binduserinfo', :on => :collection
    get 'getcode', :on => :collection
    get 'bind_form', :on => :collection
  end

  resources :announcements do
    get 'check'
    get 'check_out'
    post 'batch', :on => :collection
    get 'app_show'

    get 'warehouse_notice_index', :on => :collection
    get 'batch_check', :on => :collection
    get 'next_check', :on => :collection
    get 'next_check_out', :on => :collection
    get 'next_delete', :on => :collection
    post 'stow', :on => :collection
    post 'batch_delete', :on => :collection
    post 'announcement_hit'
  end

  resources :announcement_categories

  resources :pictures do
    post 'upload'
  end

  resources :categories

  devise_for :users, controllers: {
                       sessions: 'users/sessions',
                       registrations: 'users/registrations', #-----addby <dfj>
                   }

  devise_scope :user do
    get "users/sessions/password_reset", to: "users/sessions#password_reset"
    get "users/sessions/cheak_mobile", to: "users/sessions#cheak_mobile"
    get "users/send_message", to: "users/registrations#send_message"
    post "users/sessions/fix_password", to: "users/sessions#fix_password"
    post "users/mobile_sign_in", to: "users/mobile_sessions#create"
    post "users/mobile_sign_out", to: "users/mobile_sessions#destroy"
  end

  root to: "root#index"

  mount ElephantV1Api => '/api/v1/'

  mount ResqueWeb::Engine => "/resque"

  namespace :api do
    namespace :v1 do

      get 'products/find/:qrcode' => 'product#find'

      post 'user/register' => 'registrations#create'

      resources :products

    end
  end

  resources :products do

    get 'category_index', :on => :collection

    get 'demo', :on => :collection

    get 'demo_stress', :on => :collection

    post 'search', :on => :collection

    post 'searchByQrcode', :on => :collection

    get 'dataTablesProducts', :on => :collection

    post 'upload'

    post 'rack'

    get 'state'

    get 'page/:page', :action => :index, :on => :collection

    get 'warehouse_index', :on => :collection

    get 'statistic', :on => :collection
    get 'statisticData', :on => :collection

    get 'warehouse_show'
  end

  namespace :admin do
    post 'users/upload'
    resources :users
    post 'users/manage_store'
    get 'users/:id/reset_password' => 'users#reset_password'
    get 'users/:id/modify_loginpasswordForm' => 'users#modify_loginpasswordForm'
    post 'users/modify_loginpassword' => 'users#modify_loginpassword'
  end

  resources :mobile_categories

  resources :stores do
    get 'delivery_users'
    post 'add_delivery_user'
    post 'reduce_delivery_user'
    post 'upload'
    get 'search', :on => :collection
  end

  resources :chateaus do
    get 'turn_picture'
    post 'turn_picture_add'
    delete 'turn_picture_reduce'
    post 'turn_picture_urls'
    get 'introduce_show'
    get 'chateau_mark'
    post 'chateau_mark_add'
    delete 'chateau_mark_reduce'
    get 'check'
    get 'check_out'
    get 'search', :on => :collection
    get 'wines'
    get 'workload', :on => :collection
    post 'relate_wine'
    get 'resolve_wine'
    get 'ex_pic', :on => :collection
    get 'batch_check', :on => :collection
    get 'next_check', :on => :collection
    get 'next_check_out', :on => :collection
  end
  resources :chateau_marks

  resources :chateau_comments do
  end
  post 'chateau_comments/add_comment' => 'chateau_comments#add_comment'
  post 'chateau_comments/hit' => 'chateau_comments#hit'
  resources :regions do
    get 'children'
    post 'add_children'
    delete 'reduce_children'
    post 'get_children'
  end
  resources :wines do
    post 'table', :on => :collection
    get 'turn_picture'
    post 'turn_picture_add'
    delete 'turn_picture_reduce'
    post 'turn_picture_urls'
    get 'introduce_show'
    get 'mark'
    post 'mark_add'
    delete 'mark_reduce'
    get 'check'
    get 'check_out'
    get 'search', :on => :collection
    post 'picture_upload', :on => :collection
  end
  post 'ckeditor/pictures' => 'wines#upload'
  post 'phone_books/upload'
  get 'share_integrals/share' => 'share_integrals#share'

  resources :share_integrals do
    post 'register'
    post 'share_time_check', :on => :collection
    get 'share_integral_role'
    resources :share_integral_records

  end

  get 'dashboards/index' => 'dashboards#index'
  post 'dashboards/store_order_data' => "dashboards#store_order_data"
  post 'dashboards/exposure_product_data' => "dashboards#exposure_product_data"
  post 'dashboards/sale_product_data' => "dashboards#sale_product_data"
  get 'common/create_qrcode_image' => "common#create_qrcode_image"

  post 'jxc_stock_transfer_bills/audit'
  post 'jxc_stock_transfer_bills/strike_a_balance'
  post 'jxc_stock_transfer_bills/invalid'

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: [:show, :edit, :update, :destroy]

  # GET /stores
  # GET /stores.json
  def index
    if params[:u_id].present?
      @manage_store=params[:state]
      @user_id=params[:u_id]
      @user = User.find(params[:u_id])
      @current_user = current_user
      @store_ids = @user['store_ids']
      if @store_ids==nil
        @store_ids=[]
      end
      conditionParams = {}
      name_condition=params[:name] || ''
      conditionParams['userinfo_id'] = @user.userinfo.id
      conditionParams['name'] = /#{name_condition}/ if name_condition.present?
      @stores = Store.where(conditionParams).page(params[:page]).order('created_at DESC')
    else
      name_condition=params[:name] || ''
      conditionParams = {}
      conditionParams['name'] =  /#{name_condition}/ if name_condition.present?
      if current_user.userinfo.present?
        conditionParams['userinfo_id'] = current_user.userinfo.id
        @stores = Store.where(conditionParams).page(params[:page]).order('created_at DESC')
      else
        @stores = nil
      end
    end
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
  end

  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(store_params)
    @store.userinfo_id = current_user.userinfo.id
    respond_to do |format|
      if @store.save
        format.json { render json: get_render_common_json(@store,stores_path) }
      else
        format.json { render json: get_render_common_json(@store) }
      end
    end
  end

  def upload

  end

  # PATCH/PUT /stores/1
  # PATCH/PUT /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.json { render json: get_render_common_json(@store,stores_path) }
      else
        format.json { render json: get_render_common_json(@store) }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store.destroy
    respond_to do |format|
      format.js { render_js stores_path }
      format.html { redirect_to stores_url, notice: 'Store was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  # 门店自主选择配送员

  def delivery_users
    mobile_condition=params[:mobile] || ''
    conditionParams = {}
    conditionParams['mobile'] = /#{mobile_condition}/ if mobile_condition.present?
    conditionParams['userinfo_id'] = current_user.userinfo.id if current_user.present?
    conditionParams['status'] = 1
    @store = Store.find(params[:store_id])
    @delivery_users = DeliveryUser.where(conditionParams).page(params[:page]).order('created_at DESC')
  end


  # 配送员增加
  def add_delivery_user
    delivery_user = DeliveryUser.find(params[:delivery_user_id])
    store = Store.find(params[:store_id])
    delivery_user.stores << store
    respond_to do |format|
      if store.save && delivery_user.save
        format.js { render_js store_delivery_users_path }
        format.json { head :no_content }
      else
        format.js { render_js store_delivery_users_path }
        format.json { head :no_content }
      end
    end
  end


  # 配送员移除
  def reduce_delivery_user
    delivery_user = DeliveryUser.find(params[:delivery_user_id])
    store = Store.find(params[:store_id])
    delivery_user.stores.delete(store)
    respond_to do |format|
      if store.save && delivery_user.save
        format.js { render_js store_delivery_users_path }
        format.json { head :no_content }
      else
        format.js { render_js store_delivery_users_path }
        format.json { head :no_content }
      end
    end
  end


  private
  # Use callbacks to share common setup or constraints between actions.
  def set_store
    @store = Store.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def store_params
    params.require(:store).permit(:name, :manager, :describe, :longitude, :latitude, :position, :idpf, :idpb, :bp, :type)
  end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_form.html.haml
.hr.hr-16.hr-dotted
.row
  .container
    = form_for @store, remote:true do |f|
      #error_explanation{"style"=>"display:none"}
        %ul
      .col-xs-12
        %form.form-horizontal
          .form-group
            .field
              = f.label :门店名称,:class=>'col-sm-2 control-label no-padding-right'
            .col-sm-9
              = f.text_field :name,{:class=>'col-xs-10 col-sm-5'}
          .form-group
            .field
              = f.label :门店店长,:class=>'col-sm-2 control-label no-padding-right'
            .col-sm-9
              = f.text_field :manager,{:class=>'col-xs-10 col-sm-5'}
          .form-group
            .field
              = f.label :门店描述,:class=>'col-sm-2 control-label no-padding-right'
            .col-sm-9
              = f.text_field :describe,{:class=>'col-xs-10 col-sm-5'}
          .form-group
            .field
              = f.label :门店类型,:class=>'col-sm-2 control-label no-padding-right'
            .col-sm-9
              = f.radio_button(:type, 1)
              = f.label(:type, '实体门店')
              = f.radio_button(:type, 0)
              = f.label(:type, '虚拟门店')
          .form-group
            .field
              = f.label :门店经度,:class=>'col-sm-2 control-label no-padding-right'
            .col-sm-9
              = f.text_field :longitude,{:id => 'longitude',:class=>'col-xs-10 col-sm-5'}
          .form-group
            .field
              = f.label :门店纬度,:class=>'col-sm-2 control-label no-padding-right'
            .col-sm-9
              = f.text_field :latitude,{:id => 'latitude',:class=>'col-xs-10 col-sm-5'}
          .form-group
            .field
              = f.label :位置,:class=>'col-sm-2 control-label no-padding-right'
            .col-sm-9
              = f.text_field :position,{:id => 'position',:class=>'col-xs-10 col-sm-5'}
          .form-group
            .field
              = f.label :百度地图,:class=>'col-sm-2 control-label no-padding-right'
            .col-sm-9
              #store-map{style:'width:630px;height:230px;border:1px solid gray'}
          .form-group
            .field
              = f.label :身份证正面照片,:class=>'col-sm-2 control-label no-padding-right'
            .col-sm-9
              = f.file_field :idpf,{:id => 'store_idpf'}
              -if @store.bp.present?
                = image_tag(@store.idpf.url, size: '300x200')
          .form-group
            .field
              = f.label :身份证反面照片,:class=>'col-sm-2 control-label no-padding-right'
            .col-sm-9
              = f.file_field :idpb,{:id => 'store_idpb'}
              -if @store.bp.present?
                = image_tag(@store.idpb.url, size: '300x200')
          .form-group
            .field
              = f.label :营业执照照片,:class=>'col-sm-2 control-label no-padding-right'
            .col-sm-9
              = f.file_field :bp,{:id => 'store_bp'}
              -if @store.bp.present?
                = image_tag(@store.bp.url, size: '300x200')
              .hr.hr-16.hr-dotted
            .actions.col-sm-1.col-sm-offset-3
              = f.submit '保存',:class=> 'btn btn-success'
            .actions.col-sm-8
              = link_to '返回','', 'data-href' => stores_path,:class=> 'btn btn-info'

app/views/stores/delivery_users.html.haml
%div{class:'row',style:'background-color:#EFF3F8'}
%div{class:'col-xs-12'}
  %form#search-scope.form-inline{'method'=>'post','accept-charset'=>'UTF-8','action'=>stores_path,'data-remote'=>'true'}
    .form-group
      %label 配送员手机号:
      %input#mobile.form-control{'mobile'=>'名称'}
    %a.btn.btn-primary.btn-sm{'href'=>'javascript:delivery_users_search();'} 搜索

%table.table.table-striped.table-bordered.table-hover
  %thead
    %tr
      %th 真实姓名
      %th 手机号
      %th 创建时间
      %th op
  %tbody
    - @delivery_users.each do |delivery_user|
      %tr
        %td= delivery_user.real_name
        %td= delivery_user.mobile
        %td= delivery_user.created_at
        -if delivery_user.store_ids.include?(@store.id)
          %td
            = link_to '减少', store_reduce_delivery_user_path(:delivery_user_id=>delivery_user.id), :remote=>true, :method => :post,:class => 'btn btn-minier btn-danger'
        -else
          %td
            = link_to '增加',store_add_delivery_user_path(:delivery_user_id=>delivery_user.id), :remote=>true,:method => :post,:class => 'btn btn-minier btn-primary'
%br

%div{class:'row',style:'background-color:#EFF3F8'}
  %div{class:'col-xs-5'}
    = link_to '返回门店',"##{stores_path}",'data-href' =>stores_path,:class => 'btn btn-info'
  %div{class:'col-xs-7'}
    %div{class:'dataTables_paginate paging_simple_numbers',id:'dynamic-table_paginate'}
      %ul{class:'pagination',style:'padding-top:5px;'}
        %li{class:'paginate_button previous disabled',id:'dynamic-table_previous',"aria-controls"=>'dynamic-table',"tabindex"=>'0'}
          = paginate @delivery_users

app/views/stores/edit.html.haml
.row
  .col-sm-12.col-sm-offset-3
    %h1 门店修改
%script{type:"text/javascript",src:"http://api.map.baidu.com/api?v=2.0&ak=PxeMqAnIzuRf8UGGuQ9zNlor"}
= render 'form'

app/views/stores/index.html.haml
%h1 门店列表
%br
%div{class:'row',style:'background-color:#EFF3F8'}
  -if @user_id.present?
    %div{class:'col-xs-6'}
      %form#search-scope.form-inline{'method'=>'post','accept-charset'=>'UTF-8','action'=>stores_path,'data-remote'=>'true'}
        .form-group
          %label{"for"=>"qrcode"} 店名:
          %input#name.form-control{'name'=>'名称'}
        %a.btn.btn-primary.btn-sm{'href'=>'javascript:search();'} 搜索
        %input{"type"=>"hidden","id"=>"user_id","value"=>"#{@user_id}"}
  -else
    %div{class:'col-xs-6'}
      = link_to '新建门店',"##{new_store_path}",'data-href' =>new_store_path,:class => 'btn btn-info'
    %div{class:'col-xs-6'}
      %form#search-scope.form-inline{'method'=>'post','accept-charset'=>'UTF-8','action'=>stores_path,'data-remote'=>'true'}
        .form-group
          %label{"for"=>"qrcode"} 店名:
          %input#name.form-control{'name'=>'名称'}
        %a.btn.btn-primary.btn-sm{'href'=>'javascript:search();'} 搜索
%div
  -if @stores.present?
    %table.table.table-striped.table-bordered.table-hover
      %thead
        %tr
          %th 门店名称
          %th 门店管理者
          %th 门店类型
          %th 门店经度
          %th 门店纬度
          %th 门店位置
          %th 创建时间
          %th{:colspan => "4"}操作

      %tbody
        - @stores.each do |store|
          %tr
            %td= store.name
            %td= store.manager
            %td= store.type_str
            %td= store.longitude
            %td= store.latitude
            %td= store.position
            %td= store.created_at
            %td
              -if @user_id.present?
                -if @store_ids.include?(store.id)
                  = link_to '取消负责',"javascript:unmanage_store('"+store.id+"','"+@user_id+"')",:class => 'btn btn-xs btn-danger',:id => "unmanage_store_href#{store.id.to_s}"
                  = link_to '确认负责',"javascript:manage_store('"+store.id+"','"+@user_id+"')",:class => 'btn btn-xs btn-info',:id => "manage_store_href#{store.id.to_s}",style: 'display: none'
                -else
                  = link_to '取消负责',"javascript:unmanage_store('"+store.id+"','"+@user_id+"')",:class => 'btn btn-xs btn-danger',:id => "unmanage_store_href#{store.id.to_s}",style: 'display: none'
                  = link_to '确认负责',"javascript:manage_store('"+store.id+"','"+@user_id+"')",:class => 'btn btn-xs btn-info',:id => "manage_store_href#{store.id.to_s}"
              -else
                = link_to '详细',"##{store_path(store)}",'data-href' => store_path(store),:class => 'btn btn-minier btn-yellow'
                = link_to '编辑',"##{edit_store_path(store)}",'data-href' => edit_store_path(store),:class => 'btn btn-minier btn-primary'
                -#= link_to '配送员管理',"##{store_delivery_users_path(store)}",'data-href' => store_delivery_users_path(store),:class => 'btn btn-minier btn-primary'
                = link_to '删除', store_path(store), :remote=>true, :method => :delete, :data => { :confirm => 'Are you sure?' },:class => 'btn btn-minier btn-danger'

  -else
    %h1
      你还没有门店
  %div
    = paginate @stores
  %div
    -if @manage_store.present?
      = link_to '返回用户列表',"##{admin_users_path}",'data-href'=> admin_users_path,class:'btn btn-primary'

app/views/stores/new.html.haml
.row
  .col-sm-12.col-sm-offset-3
    %h1 门店新建
= render 'form'

app/views/stores/show.html.haml
%p#notice= notice

%p
  %b 门店名称:
  = @store.name
%p
  %b 门店管理者:
  = @store.manager
%p
  %b 门店描述:
  = @store.describe
%p
  %b 门店类型:
  = @store.type
%p
  %b 门店经度:
  = @store.longitude
%p
  %b 门店纬度:
  = @store.latitude
%p
  %b 门店位置:
  = @store.position
%p
  %b 创建时间:
  = @store.created_at
%p
%b 身份证正面照片:
= if @store.idpf.present?
  .asset
    = image_tag(@store.idpf.url,size: "300x160")
%p
%b 身份证反面照片:
= if @store.idpf.present?
  .asset
    = image_tag(@store.idpb.url,size: "300x160")
%p
%b 营业执照照片:
= if @store.bp.present?
  .asset
    = image_tag(@store.bp.url,size: "300x160")
%p
= link_to '编辑',"##{edit_store_path(@store)}",'data-href' =>edit_store_path(@store),:class => 'btn btn-info'
\|
= link_to '返回',"##{stores_path}",'data-href' =>stores_path,:class => 'btn btn-info'