config/routes.rb
Rails.application.routes.draw do

  resources :phone_books
  resources :feedbacks
  resources :roles
  resources :card_bags do

  end
  resources :clients do
    get "on_off"
  end
  resources :jxc_bill_detail
  resources :jxc_entering_stocks do
    get "prev", :on => :collection
    get "next", :on => :collection
    get "audit"
  end
  resources :product_tickets do
    get 'customers_import'
    get 'get_customers'
    post 'customer_add'
    post 'customer_reduce'
    post 'build_card_bag'
    post 'share_time_check', :on => :collection
    get 'share'
    post 'register'
    resources :product_ticket_customer_inits, shallow: true
    get 'product_ticket_role'
  end

  get '/product_ticket_customer_inits/:id/remove' => "product_ticket_customer_inits#remove" #酒劵用户移除

  get '/product_tickets/:product_ticket_id/product_ticket_customer_inits/import_customer' => "product_ticket_customer_inits#import_customer" #酒劵用户导入

  resources :user_integrals
  resources :wines

  resources :userinfo_asks
  resources :cashes
  resources :import_bags do
    resources :import_bag_receivers, shallow: true
  end
  resources :promotion_discounts do
    get 'products/:product_id/:operat/:type' => :products, :on => :collection
  end

  post 'import_bags/:import_bag_id/import_bag_receivers/batch' => "import_bag_receivers#batch" #后台收礼人批量导入
  get 'import_bags/import_bag_receivers/down_templ' => "import_bag_receivers#down_templ" #后台收礼人批量导入down_templ
  get 'gift_bags/:import_bag_id/index' => "gift_bags#index" #后台导入礼包认领情况

  post 'import_bags/products/table/data/' => "import_bags#products_table_data"
  post 'import_bags/workflow/deal' => "import_bags#deal"
  get 'import_bags/workflow/deal_list' => "import_bags#deal_list"

  resources :delivery_users
  post 'delivery_users/datatable'=> "delivery_users#datatable"
  get 'delivery_users/:id/check' => "delivery_users#check"
  post 'delivery_users/:id/check_save' => "delivery_users#check_save"
  get 'delivery_users/:id/store_index' => "delivery_users#store_index"
  post 'delivery_users/:id/store_save' => "delivery_users#store_save"

  get 'activities/skipe_one_index/:id/:platform' => 'activities#skipe_one_index'
  get 'activities/skipe_one_search'
  get 'activities/full_reduction/:userinfo_id/:full_reduction_id/:platform' => 'activities#fullReductions'
  get 'activities/promotion_discount/:userinfo_id/:promotion_discount_id/:platform' => 'activities#promotionDiscount'
  get 'activities/coupons/:userinfo_id/:platform' => 'activities#coupons'
  get 'activities/promotions/:userinfo_id/:platform' => 'activities#promotions'
  get 'activities/discount/:userinfo_id/:platform' => 'activities#discount'

  resources :coupons do
    get :invalided
    get 'products/:product_id/:operat' => :products, :on => :collection
    get :selectProducts, :on => :collection
  end
  resources :carous do
    get 'downloadS', :on => :collection
  end

  resources :full_reductions do
    get 'products/:product_id/:operat' => :products, :on => :collection
    get 'coupons/:coupon_info/:operat' => :coupons, :on => :collection
    get 'giftProducts/:product_info/:operat' => :giftProducts, :on => :collection
  end

  resources :panic_buyings do
    get 'product_list', :on => :collection
    get 'product'
    get 'panic_table', :on => :collection

    post 'add_product'
    get 'remove_product'
  end

  resources :carousels do
    post 'upload'
    delete 'destroyAsset'
    get 'downloadAsset'
  end

  mount RuCaptcha::Engine => "/rucaptcha"
  resources :userinfos do
    get 'jyd_index', :on => :collection
    get 'jyd_new', :on => :collection
    post 'jyd_create', :on => :collection
    get 'jyd_show/:userinfo_id', to: "userinfos#jyd_show", :on => :collection
    get 'jyd_edit/:userinfo_id', to: "userinfos#jyd_edit", :on => :collection
    patch 'jyd_update/:userinfo_id', to: "userinfos#jyd_update", :on => :collection
    post 'jyd_check/:userinfo_id', to: "userinfos#jyd_check", :on => :collection
    post 'jyd_check_out/:userinfo_id', to: "userinfos#jyd_check_out", :on => :collection
    delete 'jyd_destroy/:userinfo_id', to: "userinfos#jyd_destroy", :on => :collection

    get 'audit', :on => :collection
    get 'email_active/:confirmation_token', :action => :email_active, :on => :collection

    post 'userinfo_edit'

    resources :products do
      get 'desc'
      get 'preview'
    end
  end

  get "/user_mailer/signup_confirmation", :as => "user_mailer"

  resources :statistics do
    post 'search', :on => :collection
  end
  resources :cashiers do
    post 'checkCustomer', :on => :collection
  end

  resources :orders do
    resources :ordergoods
    post 'line_order_creat', :on => :collection
    get 'distribution_completed'
    get 'receive_order'

    get 'order_state_count', :on => :collection
    get 'orders_table_data', :on => :collection

    get 'statistic', :on => :collection
    get 'statisticData', :on => :collection
    post "wx_notify", :on => :member
    post "alipay_notify", :on => :member
    post "alipay_refund_notify", :on => :member
    post "alipay_dback_notify", :on => :member
    get 'line_payment_order', :on => :collection
  end

  resources :userinfo_orders do
    post 'binduserinfo', :on => :collection
    get 'getcode', :on => :collection
    get 'bind_form', :on => :collection
  end

  resources :announcements do
    get 'check'
    get 'check_out'
    post 'batch', :on => :collection
    get 'app_show'

    get 'warehouse_notice_index', :on => :collection
    get 'batch_check', :on => :collection
    get 'next_check', :on => :collection
    get 'next_check_out', :on => :collection
    get 'next_delete', :on => :collection
    post 'stow', :on => :collection
    post 'batch_delete', :on => :collection
    post 'announcement_hit'
  end

  resources :announcement_categories

  resources :pictures do
    post 'upload'
  end

  resources :categories

  devise_for :users, controllers: {
                       sessions: 'users/sessions',
                       registrations: 'users/registrations', #-----addby <dfj>
                   }

  devise_scope :user do
    get "users/sessions/password_reset", to: "users/sessions#password_reset"
    get "users/sessions/cheak_mobile", to: "users/sessions#cheak_mobile"
    get "users/send_message", to: "users/registrations#send_message"
    post "users/sessions/fix_password", to: "users/sessions#fix_password"
    post "users/mobile_sign_in", to: "users/mobile_sessions#create"
    post "users/mobile_sign_out", to: "users/mobile_sessions#destroy"
  end

  root to: "root#index"

  mount ElephantV1Api => '/api/v1/'

  mount ResqueWeb::Engine => "/resque"

  namespace :api do
    namespace :v1 do

      get 'products/find/:qrcode' => 'product#find'

      post 'user/register' => 'registrations#create'

      resources :products

    end
  end

  resources :products do

    get 'category_index', :on => :collection

    get 'demo', :on => :collection

    get 'demo_stress', :on => :collection

    post 'search', :on => :collection

    post 'searchByQrcode', :on => :collection

    get 'dataTablesProducts', :on => :collection

    post 'upload'

    post 'rack'

    get 'state'

    get 'page/:page', :action => :index, :on => :collection

    get 'warehouse_index', :on => :collection

    get 'statistic', :on => :collection
    get 'statisticData', :on => :collection

    get 'warehouse_show'
  end

  namespace :admin do
    post 'users/upload'
    resources :users
    post 'users/manage_store'
    get 'users/:id/reset_password' => 'users#reset_password'
    get 'users/:id/modify_loginpasswordForm' => 'users#modify_loginpasswordForm'
    post 'users/modify_loginpassword' => 'users#modify_loginpassword'
  end

  resources :mobile_categories

  resources :stores do
    get 'delivery_users'
    post 'add_delivery_user'
    post 'reduce_delivery_user'
    post 'upload'
    get 'search', :on => :collection
  end

  resources :chateaus do
    get 'turn_picture'
    post 'turn_picture_add'
    delete 'turn_picture_reduce'
    post 'turn_picture_urls'
    get 'introduce_show'
    get 'chateau_mark'
    post 'chateau_mark_add'
    delete 'chateau_mark_reduce'
    get 'check'
    get 'check_out'
    get 'search', :on => :collection
    get 'wines'
    get 'workload', :on => :collection
    post 'relate_wine'
    get 'resolve_wine'
    get 'ex_pic', :on => :collection
    get 'batch_check', :on => :collection
    get 'next_check', :on => :collection
    get 'next_check_out', :on => :collection
  end
  resources :chateau_marks

  resources :chateau_comments do
  end
  post 'chateau_comments/add_comment' => 'chateau_comments#add_comment'
  post 'chateau_comments/hit' => 'chateau_comments#hit'
  resources :regions do
    get 'children'
    post 'add_children'
    delete 'reduce_children'
    post 'get_children'
  end
  resources :wines do
    post 'table', :on => :collection
    get 'turn_picture'
    post 'turn_picture_add'
    delete 'turn_picture_reduce'
    post 'turn_picture_urls'
    get 'introduce_show'
    get 'mark'
    post 'mark_add'
    delete 'mark_reduce'
    get 'check'
    get 'check_out'
    get 'search', :on => :collection
    post 'picture_upload', :on => :collection
  end
  post 'ckeditor/pictures' => 'wines#upload'
  post 'phone_books/upload'
  get 'share_integrals/share' => 'share_integrals#share'

  resources :share_integrals do
    post 'register'
    post 'share_time_check', :on => :collection
    get 'share_integral_role'
    resources :share_integral_records

  end

  get 'dashboards/index' => 'dashboards#index'
  post 'dashboards/store_order_data' => "dashboards#store_order_data"
  post 'dashboards/exposure_product_data' => "dashboards#exposure_product_data"
  post 'dashboards/sale_product_data' => "dashboards#sale_product_data"
  get 'common/create_qrcode_image' => "common#create_qrcode_image"

  post 'jxc_stock_transfer_bills/audit'
  post 'jxc_stock_transfer_bills/strike_a_balance'
  post 'jxc_stock_transfer_bills/invalid'

app/models/userinfo.rb
class Userinfo
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Paperclip
  include Mongoid::Geospatial

  has_many :orders
  has_many :ordercompleteds
  has_many :users
  has_many :delivery_users
  has_many :userinfo_asks
  has_many :user_integrals
  has_many :userinfo_oppenids
  has_many :share_integrals
  has_many :product_tickets
  has_many :jxc_storage  #进销存仓库


  has_and_belongs_to_many :keywords

  has_many :fullReductions
  has_many :promotionDiscounts
  has_many :coupons
  has_many :mobile_categories

  field :name, type: String # 经营者姓名1
  field :idnumber, type: String#身份证号码1

  field :alipay,type: String #支付宝账号
  field :alipay_name,type: String#支付宝姓名

  field :wx_name,type: String,default: "" #微信实名制姓名(即微信绑定银行卡的姓名)
  field :openid,type: String,default: "" #转账唯一标示

  field :address, type: String,default: "" # 经营者地址1
  field :province,type:String ,default: ""  #省1
  field :city,type:String ,default: ""      #市区1
  field :district,type: String ,default: "" #县、区1

  field :shopname, type: String # 经营者商店名称1
  field :location, type: Point, spatial: true, default: []
  field :email, type: String #邮箱 唯一

  field :status, type: Integer,  default: 0 #启用状态，0初始化，1启用，-1禁用1

  field :integral, type: Integer,default: 0 # 积分
  field :approver,type: String #审批人
  field :pusher,type: String #推送人
  field :pusher_phone,type: String #推送人电话
  field :location_data,type: String #周围小B经纬度和配送距离

  # field :cash_pw,type: String #提现密码
  field :work_24,type: String,default: 'false' #24小时店 true／false

  field :alarm_stock, type: Integer,default: 10 # 预警库存数量1

 # field :busp_url, type: String # 营业执照
 # field :footp_url, type: String # 食品流通许可证
 # field :healthp_url, type: String # 卫生许可证
 # field :taxp_url, type: String # 税务登记证
 # field :orgp_url, type: String # 组织机构代码证
 # field :idf_url, type: String # 身份真正面
 # field :idb_url, type: String # 身份证反面
  field :pdistance_state,type: Integer,default: 0  #0/1
  field :pdistance, type: Integer,default: 0 #配送距离
  field :pdistance_ask, type: Integer,default: 0
  field :fright_time,type: String #日间配送时间点
  field :night_time,type: String #夜间配送时间点
  field :fright, type: Integer,default: 0 # 运费1
  field :lowestprice, type: Integer,default: 0 # 最低起送价格1
  field :h_fright, type: Integer,default: 0 # 运费h
  field :h_lowestprice, type: Integer,default: 0 # 最低起送价格h
  field :start_business, type: String  #营业开始时间
  field :end_business, type: String #营业结束时间
  field :channel_ids, type:Array,default: [] #移动设备推送IDs
  field :role_marks, type:Array,default: [] #角色标识 business: 运营商角色（对运营商），platform：平台角色（对平台）
  validate :position_check
  validates :name,:province,:city,:email,:shopname, presence: true #名称，种类不能为空
  validates :email,uniqueness: true #邮箱唯一
  validates :pusher_phone,presence: true,uniqueness: true,format: {with: /\A\d{11}\z/, message: "不合法!"}
  validates :idnumber,presence: true,uniqueness: true,format: {with: /\A(\A\d{15}\z|\A\d{18}\z|\A\d{17}(\d|X|x))\z/, message: "不合法!"}
  index({location: "2d"}, {min: -200, max: 200})

  has_mongoid_attached_file :busp,:default_url => '/missing.png'
  validates_attachment_content_type :busp, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  has_mongoid_attached_file :footp,:default_url => '/missing.png'
  validates_attachment_content_type :footp, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  has_mongoid_attached_file :healthp,:default_url => '/missing.png'
  validates_attachment_content_type :healthp, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  has_mongoid_attached_file :taxp,:default_url => '/missing.png'
  validates_attachment_content_type :taxp, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  has_mongoid_attached_file :orgp, :default_url => '/missing.png'
  validates_attachment_content_type :orgp, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  has_mongoid_attached_file :idpf,:default_url => '/missing.png'
  validates_attachment_content_type :idpf, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  has_mongoid_attached_file :idpb, :default_url => '/missing.png'
  # ,
  #                           :path => "public/upload/image:class/:id/:filename",
  #                           :url => "/upload/image/:class/:id/:basename.:extension"
  validates_attachment_content_type :idpb, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  #轮播图
  field :img_path1,type: String
  field :img_path2,type: String
  field :url1,type: String
  field :url2,type: String
  field :url3,type: String
  field :url4,type: String

  has_mongoid_attached_file :aseet1, :default_url => '/missing.png',
                            :url => "/upload/image/carousel/:class/:id.:extension",
                            :path => "public:url"
  validates_attachment_content_type :aseet1, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  has_mongoid_attached_file :aseet2, :default_url => '/missing.png',
                            :url => "/upload/image/carousel/:class/:id.:extension",
                            :path => "public:url"
  validates_attachment_content_type :aseet2, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]



  attr_accessor :lng, :lat

  def integral_update(integral)
    self.update_attributes(:integral => integral) #积分核增
  end




  def status_str
    if self.status==0
      p '未启用'
    elsif self.status==1
      p '启用'
    else
      p '停用'
    end
  end


  #联盟商省市区唯一
  def position_check
    userinfo = Userinfo.where(:province=>self.province,:city=>self.city,:district=>self.district,:id=>{'$ne'=>self.id}).first
    if userinfo.present?
      if self.district.present?
        errors.add(:district, "已经存在联盟商,请进行修改!")
      else
        errors.add(:city, "已经存在联盟商,请进行修改!")
      end
    end
  end


  class << self
    def nearby(coordinate, max_distance=5)
      # 5公里内， 符合条件的记录， 默认取100个。同时会按照距离的远近 进行排序。
      self.geo_near(coordinate).max_distance(max_distance.fdiv   6371).spherical.distance_multiplier(6371000)
    end
  end

end

app/helpers/userinfos_helper.rb
module UserinfosHelper
end

app/views/userinfos/_jyd_form.html.haml
.hr.hr-16.hr-dotted
.row
  .container
    = form_for @userinfo, url: {action: @params_action},remote:true do |f|
      #error_explanation{"style"=>"display:none"}
        %ul
      .col-xs-12
        %form.form-horizontal
          .form-group
            .field
              = f.label :法人姓名,:class=>'col-sm-2 control-label no-padding-right'
            .col-sm-9
              = f.text_field :name,{:class=>'form-control'}
          .form-group
            .field
              = f.label :身份证号码,:class=>'col-sm-2 control-label no-padding-right'
            .col-sm-9
              = f.text_field :idnumber,{:class=>'form-control'}
          .form-group
            .field
              = f.label :地址,:class=>'col-sm-2 control-label no-padding-right'
            .col-sm-9
              = f.text_field :address,{:class=>'form-control'}
          .form-group
            .field
              = f.label :省,:class=>'col-sm-2 control-label no-padding-right'
            .col-sm-9
              = f.text_field :province,{:class=>'form-control'}
            .field
              = f.label :市,:class=>'col-sm-2 control-label no-padding-right'
            .col-sm-9
              = f.text_field :city,{:class=>'form-control'}
            .field
              = f.label :区县,:class=>'col-sm-2 control-label no-padding-right'
            .col-sm-9
              = f.text_field :district,{:class=>'form-control'}
          .form-group
            .field
              = f.label :公司名称,:class=>'col-sm-2 control-label no-padding-right'
            .col-sm-9
              = f.text_field :shopname,{:class=>'form-control'}
          .form-group
            .field
              = f.label :手机号码,:class=>'col-sm-2 control-label no-padding-right'
            .col-sm-9
              = f.text_field :pusher_phone,{:class=>'form-control'}
          .form-group
            .field
              = f.label :邮箱,:class=>'col-sm-2 control-label no-padding-right'
            .col-sm-9
              = f.text_field :email,{:class=>'form-control'}
          .form-group
            .field
              = f.label :默认运费,:class=>'col-sm-2 control-label no-padding-right'
            .col-sm-9
              = f.number_field :fright,{:class=>'form-control'}
          .form-group
            .field
              = f.label :默认起送价格,:class=>'col-sm-2 control-label no-padding-right'
            .col-sm-9
              = f.number_field :lowestprice,{:class=>'form-control'}
          .form-group
            .field
              = f.label :预警库存数量,:class=>'col-sm-2 control-label no-padding-right'
            .col-sm-9
              = f.number_field :alarm_stock,{:class=>'form-control'}

          .form-group
            .field
              = f.label :百度地图,:class=>'col-sm-2 control-label no-padding-right'
            .col-sm-9
              #userinfo_map{style:'width:630px;height:230px;border:1px solid gray'}
              .hr.hr-16.hr-dotted
            .actions.col-sm-1.col-sm-offset-3
              = f.submit '保存',:class=> 'btn btn-success'
            .actions.col-sm-8
              -if current_user.has_role?(:SuperAdmin)
                = link_to '返回','','data-href' =>jyd_index_userinfos_path,:class => 'btn btn-info'
              -else
                = link_to '返回','','data-href' => nil,:class => 'btn btn-info'


:javascript
    //jquery 初始化函数
  $(function () {



    var userinfo_city = $('#userinfo_city').val();

    var map = new BMap.Map("userinfo_map");//初始化地图
    map.addControl(new BMap.NavigationControl());  //初始化地图控件
    map.enableScrollWheelZoom();    //启用滚轮放大缩小，默认禁用
    map.enableContinuousZoom();    //启用地图惯性拖拽，默认禁用
    map.addControl(new BMap.NavigationControl());  //添加默认缩放平移控件


    if (userinfo_city == "" || userinfo_city == undefined) {
      var point = new BMap.Point(113.663221, 34.7568711);
      map.centerAndZoom(point, 15);//初始化地图中心点
    }
    else{
      map.centerAndZoom(userinfo_city,15);


    }

    var point = new BMap.Point(113.663221, 34.7568711);
    map.centerAndZoom(point, 15);//初始化地图中心点

    var gc = new BMap.Geocoder();//地址解析类

    //添加标记点击监听
    map.addEventListener("click", function (e) {
      gc.getLocation(e.point, function (rs) {

        var addComp = rs.addressComponents;
        $('#userinfo_address').val(addComp.province  + addComp.city + addComp.district  + addComp.street  + addComp.streetNumber);
        $('#userinfo_province').val(addComp.province);
        $('#userinfo_city').val(addComp.city);
        $('#userinfo_district').val(addComp.district);
      });

    });


    common_form_ajax_deal();

  });

app/views/userinfos/audit.html.erb
<!doctype html>

<html xmlns="http://www.w3.org/1999/html">

<head>
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
  <meta charset="utf-8"/>

  <title><%= content_for?(:title) ? yield(:title) : "Lark" %></title>

  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0"/>

  <%= csrf_meta_tags %>

  <script type="text/javascript" src="http://api.map.baidu.com/api?v=2.0&ak=PxeMqAnIzuRf8UGGuQ9zNlor"></script>


  <%= javascript_include_tag "application" %>
  <%= stylesheet_link_tag "rediscss/regissh.css" %>

</head>
<body>
<!--header-->
<div class="header">
  <div class="hbox">
    <%= image_tag("img01.png") %><div class="ahb">
    <div class="ahb01"></div>
    <div class="ahb02">
      <div class="ahb0201"><%= current_user.mobile %></div>
      <%= image_tag ("img15.png"),:class=>"ahb0202" %>
      <div class="ahb0203"><%= link_to raw("<i class='qq_close'></i>退出"), destroy_user_session_path, :method=>'delete' %></div>
    </div>
  </div>

  </div>

</div>
<!--内容-->
<div class="zz">
  <div class="nav">
    <div class="na01">
      <div class="na0101">1、基本信息</div>
    </div>
    <div class="na02">
      <div class="na0201">2、邮箱激活</div>
    </div>
    <div class="na03">
      <div class="na0301">3、信息登记</div>
    </div>
    <div class="na04">
      <div class="na0401">4、审核</div>
    </div>
  </div>

  <div class="nr">
    <div class="nr01">
      <div class="nr0101">
        <%= image_tag("img05.png") %>
      </div>
      <div class="nr0102">审核中 . . .</div>
    </div>
    <div class="nr02">对不起，你提交的信息正在审核中，我们会在24小时内以邮件方式发到你的邮箱中，请注意查收！</div>
  </div>
</div>

<!--footer-->
<div class="footer">
  <div class="ftbox">
    <div class="ft01">
      <a href="">关于我们</a>
      <%= image_tag("img06.png") %>
    </div>
    <div class="ft01">
      <a href="">服务协议</a>
      <%= image_tag("img06.png") %>
    </div>
    <div class="ft01">
      <a href="">运营规范</a>
      <%= image_tag("img06.png") %>
    </div>
    <div class="ft01">
      <a href="">辟谣中心</a>
      <%= image_tag("img06.png") %>
    </div>
    <div class="ft01">
      <a href="">客服中心</a>
      <%= image_tag("img06.png") %>
    </div>
    <div class="ft01">
      <a href="">联系邮箱</a>
      <%= image_tag("img06.png") %>
    </div>
    <div class="ft01">
      <a href="">侵权投诉</a>
      <%= image_tag("img06.png") %>
    </div>
    <div class="ft02">
      <a>Copyright<span style="font-family:'Arial';">&copy;</span>2012-2015  tencent. All  Rights  Reserved.</a>
    </div>
  </div>
</div>
</body>
</html>

app/views/userinfos/jyd_edit.html.haml
= render 'jyd_form'

app/views/userinfos/jyd_index.html.haml
%h1 联盟商列表
%br
%div{class:'row',style:'background-color:#EFF3F8'}
  %div{class:'col-xs-9'}
    = link_to '新建联盟商',"##{jyd_new_userinfos_path}",'data-href' =>jyd_new_userinfos_path,:class => 'btn btn-info'
  %div{class:'col-xs-3'}
    %form#search-scope.form-inline{'method'=>'post','accept-charset'=>'UTF-8','action'=>stores_path,'data-remote'=>'true'}
      .form-group
        %label{"for"=>"qrcode"} 公司名称:
        %input#name.form-control{'name'=>'名称'}
      %a.btn.btn-primary.btn-sm{'href'=>'javascript:search();'} 搜索
%table.table.table-striped.table-bordered.table-hover
  %thead
    %tr
      %th 公司名称
      %th 法人名称
      %th 法人手机号码
      %th 公司地址
      %th 公司状态
      %th
  %tbody
    - @userinfos.each do |userinfo|
      %tr
        %td= userinfo.shopname
        %td= userinfo.name
        %td= userinfo.pusher_phone
        %td= userinfo.address
        %td= userinfo.status_str
        %td
          = link_to '详细',"",'data-href' => '/userinfos/jyd_show/'+ userinfo.id,:class => 'btn btn-minier btn-info'
          = link_to '编辑',"",'data-href' => '/userinfos/jyd_edit/'+ userinfo.id,:class => 'btn btn-minier btn-primary'
          -if userinfo.status==0||userinfo.status==-1
            = link_to '启用', '/userinfos/jyd_check/'+ userinfo.id, :remote=>true, :method => :post,:class => 'btn btn-minier btn-primary'
          -else
            = link_to '停用','/userinfos/jyd_check_out/'+ userinfo.id, :remote=>true, :method => :post,:class => 'btn btn-minier btn-warning'
          -#= link_to '删除', 'userinfos/jyd_destroy/'+userinfo.id, :remote=>true, :method => :delete, :data => { :confirm => 'Are you sure?' },:class => 'btn btn-minier btn-danger'
= paginate @userinfos



:javascript


      //jquery 初始化函数
  $(function () {
    pagination_ajax();
  });


    //查询
  function search() {
    var name = $("#search-scope #name").val();
    var prefix_url = "?name=" + name;
    window.location.href = get_location_href_no_search() + prefix_url + "&f=" + get_rand_num();
  }

app/views/userinfos/jyd_new.html.haml
.row
  .col-sm-12.col-sm-offset-3
    %h1 联盟商新建
= render 'jyd_form'

app/views/userinfos/jyd_show.html.haml
%p
  %b 公司名称:
  = @userinfo.shopname
%p
  %b 法人姓名:
  = @userinfo.name
%p
  %b 法人身份证号:
  = @userinfo.idnumber
%p
  %b 公司地址:
  = @userinfo.address
%p
  %b 法人手机号码:
  = @userinfo.pusher_phone
%p
  %b 公司状态:
  = @userinfo.status_str
%p
  %b 默认运费:
  = @userinfo.fright
%p
  %b 默认起送价格:
  = @userinfo.lowestprice
%p
  %b 预警库存数量:
  = @userinfo.alarm_stock
%p
= link_to '编辑',"",'data-href' =>'/userinfos/jyd_edit/'+ @userinfo.id,:class => 'btn btn-info'
\|
-if current_user.has_role?(:SuperAdmin)
  = link_to '返回',"",'data-href' =>jyd_index_userinfos_path,:class => 'btn btn-info'
-else
  = link_to '返回',"",'data-href' => '/userinfos/jyd_edit/'+@userinfo.id,:class => 'btn btn-info'