config/routes.rb
    get 'jyd_index', :on => :collection
    get 'jyd_new', :on => :collection
    post 'jyd_create', :on => :collection
    get 'jyd_show/:userinfo_id', to: "userinfos#jyd_show", :on => :collection
    get 'jyd_edit/:userinfo_id', to: "userinfos#jyd_edit", :on => :collection
    patch 'jyd_update/:userinfo_id', to: "userinfos#jyd_update", :on => :collection
    post 'jyd_check/:userinfo_id', to: "userinfos#jyd_check", :on => :collection
    post 'jyd_check_out/:userinfo_id', to: "userinfos#jyd_check_out", :on => :collection
    delete 'jyd_destroy/:userinfo_id', to: "userinfos#jyd_destroy", :on => :collection

    get 'audit', :on => :collection
    get 'email_active/:confirmation_token', :action => :email_active, :on => :collection

    post 'userinfo_edit'

    resources :products do
      get 'desc'
      get 'preview'
    end
  end

  get "/user_mailer/signup_confirmation", :as => "user_mailer"

  resources :statistics do
    post 'search', :on => :collection
  end
  resources :cashiers do
    post 'checkCustomer', :on => :collection
  end

  resources :orders do
    resources :ordergoods
    post 'line_order_creat', :on => :collection
    get 'distribution_completed'
    get 'receive_order'

    get 'order_state_count', :on => :collection
    get 'orders_table_data', :on => :collection

    get 'statistic', :on => :collection
    get 'statisticData', :on => :collection
    post "wx_notify", :on => :member
    post "alipay_notify", :on => :member
    post "alipay_refund_notify", :on => :member
    post "alipay_dback_notify", :on => :member
    get 'line_payment_order', :on => :collection
  end

  resources :userinfo_orders do
    post 'binduserinfo', :on => :collection
    get 'getcode', :on => :collection
    get 'bind_form', :on => :collection
  end

  resources :announcements do
    get 'check'
    get 'check_out'
    post 'batch', :on => :collection
    get 'app_show'

    get 'warehouse_notice_index', :on => :collection
    get 'batch_check', :on => :collection
    get 'next_check', :on => :collection
    get 'next_check_out', :on => :collection
    get 'next_delete', :on => :collection
    post 'stow', :on => :collection
    post 'batch_delete', :on => :collection
    post 'announcement_hit'
  end

  resources :announcement_categories

  resources :pictures do
    post 'upload'
  end

  resources :categories

  devise_for :users, controllers: {
                       sessions: 'users/sessions',
                       registrations: 'users/registrations', #-----addby <dfj>
                   }

  devise_scope :user do
    get "users/sessions/password_reset", to: "users/sessions#password_reset"
    get "users/sessions/cheak_mobile", to: "users/sessions#cheak_mobile"
    get "users/send_message", to: "users/registrations#send_message"
    post "users/sessions/fix_password", to: "users/sessions#fix_password"
    post "users/mobile_sign_in", to: "users/mobile_sessions#create"
    post "users/mobile_sign_out", to: "users/mobile_sessions#destroy"
  end

  root to: "root#index"

  mount ElephantV1Api => '/api/v1/'

  mount ResqueWeb::Engine => "/resque"

  namespace :api do
    namespace :v1 do

      get 'products/find/:qrcode' => 'product#find'

      post 'user/register' => 'registrations#create'

      resources :products

    end
  end

  resources :products do

    get 'category_index', :on => :collection

    get 'demo', :on => :collection

    get 'demo_stress', :on => :collection

    post 'search', :on => :collection

    post 'searchByQrcode', :on => :collection

    get 'dataTablesProducts', :on => :collection

    post 'upload'

    post 'rack'

    get 'state'

    get 'page/:page', :action => :index, :on => :collection

    get 'warehouse_index', :on => :collection

    get 'statistic', :on => :collection
    get 'statisticData', :on => :collection

    get 'warehouse_show'
  end

  namespace :admin do
    post 'users/upload'
    resources :users
    post 'users/manage_store'
    get 'users/:id/reset_password' => 'users#reset_password'
    get 'users/:id/modify_loginpasswordForm' => 'users#modify_loginpasswordForm'
    post 'users/modify_loginpassword' => 'users#modify_loginpassword'
  end

  resources :mobile_categories

  resources :stores do
    get 'delivery_users'
    post 'add_delivery_user'
    post 'reduce_delivery_user'
    post 'upload'
    get 'search', :on => :collection
  end

  resources :chateaus do
    get 'turn_picture'
    post 'turn_picture_add'
    delete 'turn_picture_reduce'
    post 'turn_picture_urls'
    get 'introduce_show'
    get 'chateau_mark'
    post 'chateau_mark_add'
    delete 'chateau_mark_reduce'
    get 'check'
    get 'check_out'
    get 'search', :on => :collection
    get 'wines'
    get 'workload', :on => :collection
    post 'relate_wine'
    get 'resolve_wine'
    get 'ex_pic', :on => :collection
    get 'batch_check', :on => :collection
    get 'next_check', :on => :collection
    get 'next_check_out', :on => :collection
  end
  resources :chateau_marks

  resources :chateau_comments do
  end
  post 'chateau_comments/add_comment' => 'chateau_comments#add_comment'
  post 'chateau_comments/hit' => 'chateau_comments#hit'
  resources :regions do
    get 'children'
    post 'add_children'
    delete 'reduce_children'
    post 'get_children'
  end
  resources :wines do
    post 'table', :on => :collection
    get 'turn_picture'
    post 'turn_picture_add'
    delete 'turn_picture_reduce'
    post 'turn_picture_urls'
    get 'introduce_show'
    get 'mark'
    post 'mark_add'
    delete 'mark_reduce'
    get 'check'
    get 'check_out'
    get 'search', :on => :collection
    post 'picture_upload', :on => :collection
  end
  post 'ckeditor/pictures' => 'wines#upload'
  post 'phone_books/upload'
  get 'share_integrals/share' => 'share_integrals#share'

  resources :share_integrals do
    post 'register'
    post 'share_time_check', :on => :collection
    get 'share_integral_role'
    resources :share_integral_records

  end

  get 'dashboards/index' => 'dashboards#index'
  post 'dashboards/store_order_data' => "dashboards#store_order_data"
  post 'dashboards/exposure_product_data' => "dashboards#exposure_product_data"
  post 'dashboards/sale_product_data' => "dashboards#sale_product_data"
  get 'common/create_qrcode_image' => "common#create_qrcode_image"

  post 'jxc_stock_transfer_bills/audit'
  post 'jxc_stock_transfer_bills/strike_a_balance'
  post 'jxc_stock_transfer_bills/invalid'
  resources :jxc_stock_transfer_bills

  post 'jxc_stock_reduce_bills/audit'
  post 'jxc_stock_reduce_bills/strike_a_balance'
  post 'jxc_stock_reduce_bills/invalid'
  resources :jxc_stock_reduce_bills

  post 'jxc_stock_overflow_bills/audit'
  post 'jxc_stock_overflow_bills/strike_a_balance'
  post 'jxc_stock_overflow_bills/invalid'
  resources :jxc_stock_overflow_bills

  post 'jxc_stock_count_bills/audit_in_advance'
  post 'jxc_stock_count_bills/generate_pl_bill'
  post 'jxc_stock_count_bills/finally_confirm'
  post 'jxc_stock_count_bills/invalid'
  resources :jxc_stock_count_bills

  post 'jxc_stock_assign_bills/audit'
  post 'jxc_stock_assign_bills/strike_a_balance'
  post 'jxc_stock_assign_bills/invalid'
  resources :jxc_stock_assign_bills

  resources :jxc_sell_exchange_goods_bills

  post 'jxc_sell_returns_bills/audit'
  post 'jxc_sell_returns_bills/strike_a_balance'
  post 'jxc_sell_returns_bills/invalid'
  resources :jxc_sell_returns_bills

  post 'jxc_sell_stock_out_bills/audit'
  post 'jxc_sell_stock_out_bills/strike_a_balance'
  post 'jxc_sell_stock_out_bills/invalid'
  post 'jxc_sell_stock_out_bills/generate_sell_out_bill'
  resources :jxc_sell_stock_out_bills

  post 'jxc_sell_orders/audit'
  post 'jxc_sell_orders/strike_a_balance'
  post 'jxc_sell_orders/invalid'
  resources :jxc_sell_orders

  resources :jxc_purchase_exchange_goods_bills

  post 'jxc_purchase_returns_bills/audit'
  post 'jxc_purchase_returns_bills/strike_a_balance'
  post 'jxc_purchase_returns_bills/invalid'
  resources :jxc_purchase_returns_bills

  post 'jxc_purchase_stock_in_bills/audit'
  post 'jxc_purchase_stock_in_bills/strike_a_balance'
  post 'jxc_purchase_stock_in_bills/invalid'
  resources :jxc_purchase_stock_in_bills

  post 'jxc_purchase_orders/audit'
  post 'jxc_purchase_orders/strike_a_balance'
  post 'jxc_purchase_orders/invalid'
  resources :jxc_purchase_orders

  post 'jxc_other_stock_out_bills/audit'
  post 'jxc_other_stock_out_bills/strike_a_balance'
  post 'jxc_other_stock_out_bills/invalid'
  resources :jxc_other_stock_out_bills

  post 'jxc_other_stock_in_bills/audit'
  post 'jxc_other_stock_in_bills/strike_a_balance'
  post 'jxc_other_stock_in_bills/invalid'
  resources :jxc_other_stock_in_bills

  post 'jxc_cost_adjust_bills/audit'
  post 'jxc_cost_adjust_bills/strike_a_balance'
  post 'jxc_cost_adjust_bills/invalid'
  resources :jxc_cost_adjust_bills

  resources :expired_warning_products #商品过期预警

  resources :inventory_warning_products #商品库存预警

  resources :jxc_dictionaries #字典项

  resources :jxc_product_classify_standards #商品收益分类标准

  resources :jxc_contacts_units #往来单位

  resources :jxc_storages #仓库

  resources :traceabilities do
    get 'subcode',:on=> :collection
    get 'origincode',:on=> :collection
    get 'print',:on=> :collection
  end

  get 'jxc_inventory_query/inventory_index'
  get 'jxc_inventory_query/inventory_query'
  get 'jxc_inventory_query/inventory_detail'
  get 'jxc_inventory_query/checkInventoryChangeLog' #查询库存变更日志
  get 'jxc_common_info/getSuppliersInfo' #供应商
  get 'jxc_common_info/getConsumersInfo' #客户
  get 'jxc_common_info/getStorageTypesInfo' #仓库类型
  get 'jxc_common_info/getStorageInfo' #仓库
  get 'jxc_common_info/getJxcAccountsInfo' #进销存账户
  get 'jxc_common_info/getProductCategoriesInfo' #商品分类
  get 'jxc_common_info/getProductsInfo' #商品
  get 'jxc_common_info/getAccountingItemsInfo' #会计科目
  get 'jxc_common_info/getJxcUnitCategoriesInfo' #进销存往来单位类别
  get 'jxc_common_info/getStorageTypesInfo' #仓库类别

app/models/category.rb
class Category
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Attributes::Dynamic

  belongs_to :parent, :class_name => "Category",:foreign_key => :parent_id

  has_many :childs, :class_name => "Category"

  has_and_belongs_to_many :products

  field :title
  field :form
  field :desc
  field :field

  validates :title, presence: true, uniqueness: true

  #validates :form, uniqueness: true

  def text
    title
  end

  def type
    if childs.count > 0
      'folder'
    else
      'item'
    end

  end

  def isLeaf?
    childs.count == 0
  end

  def additionalParameters
    array = []

    ids = {}
    ids[:id] = id
    ids[:children] = childs.count > 0

    array << ids
  end

  def detail
    array = []

    item = self

    while not item.parent.blank? do
      array << item.title
      item = item.parent
    end

    array.reverse
  end

  # def as_json(options={})
  #   super(:include => [:text, :type, :additionalParameters])
  # end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        if @category.field.blank?
          ProductConfig::DYNAMIC_FIELDS.delete(@category.form)
        else
          ProductConfig::DYNAMIC_FIELDS.merge!(YAML.load(@category.field))
        end

        p ProductConfig::DYNAMIC_FIELDS
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:title, :desc, :form, :field, :parent_id)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for @category, :html => {:class => 'form-horizontal category'} do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



    <div class="form-group">
      <label class = 'col-sm-3 control-label no-padding-right'>父类别</label>
      <div class="col-sm-3" style="display:inline-flex" id="select-parent-category">
        <% @rootCategory = Category.first %>
        <input type="hidden" id="rootID" value="<%= @rootCategory.id %>">
        <% @subCategories = Category.where(:parent_id => @rootCategory.id) %>
        <% if @subCategories.length <= 0 %>
        <%= f.select :_parent_id , [[Category.first.title,Category.first.id]],{:selected => @category.parent_id},{:class => 'select1 tag-input-style'}%>
        <% end %>
        <%= f.select :_parent_id , @subCategories.reverse.map { |s| [s.title, s.id] }, {:selected => @category.parent_id,:prompt => "==根类=="}, {:class => 'select2 tag-input-style'} %>

        <%= f.hidden_field :parent_id%>
      </div>
    </div>


    <div class="form-group">
      <%= f.label :title, :class => 'col-sm-3 control-label no-padding-right' %>
      <div class="col-sm-3">
        <%= f.text_field :title, :class => 'form-control' %>
      </div>
    </div>

    <div class="space-4"></div>

    <div class="form-group">
      <%= f.label :form, class:'col-sm-3 control-label no-padding-right' %>
      <div class="col-sm-3">
      <%= f.text_field :form, class:'form-control' %>
      </div>
    </div>

    <div class="space-4"></div>

    <div class="form-group">
      <%= f.label :desc, class:'col-sm-3 control-label no-padding-right' %>
      <div class="col-sm-3">
      <%= f.text_field :desc, class:'form-control' %>
      </div>
    </div>


    <div class="widget-box">
      <div class="widget-header">
        <h4 class="widget-title">添加字段</h4>
      </div>

      <div class="widget-body">
        <div class="widget-main">
            <input id="name" name="name" type="text" class="input-small" placeholder="字段名称">
            <input type="text" class="input-small" placeholder="英文名称">

            类型:<select id="type" ><option value="text">文本</option><option value="integer">整数</option><option value="date">日期</option></select>

            <button id="add" type="button" class="btn btn-info btn-sm">
              <i class="ace-icon fa fa-key bigger-110"></i>添加
            </button>
        </div>
      </div>
    </div>

    <div>
      <%= f.label :field %><br>
      <%= f.text_area :field, :class=>"autosize-transition form-control", :style=>"overflow: hidden; word-wrap: break-word; resize: horizontal; height: 200px;" %>
    </div>


    <div class="clearfix form-actions">
      <div class="col-md-offset-4 col-md-9">
        <button class="btn btn-info" id="save_form" type="submit">
          <i class="ace-icon fa fa-check bigger-110"></i>
          保存
        </button>

        &nbsp; &nbsp; &nbsp;
        <a class="btn" href="<%= categories_path %>">
          <i class="ace-icon fa fa-return bigger-110"></i>
          返回
        </a>
      </div>
    </div>
<% end %>


<script>
    $(document).ready(function () {
        parentCategory();

        $('#add').click(function () {
            var name = $('#name');
            var ename = $('#ename');
            var type = $('#type');

            var field = $('#type_field')
            var str = "\r\n" + "  " + ename.val() + ":";
            str += "\r\n" + "    zh-CN: " + name.val();
            str += "\r\n" + "    type: " + type.val();
            field.val(field.val() + str)

            name.val('')
            ename.val('')
        });

        $('.select2.tag-input-style').change(function(){
            choseCategory(this);
        });


        $('.tag-input-style').change(function(){
            parentCategory();
        });

    });

        function choseCategory(obj){
            $("#select-parent-category").children('.select3').remove();
            var categoryID = $(obj).children('option:checked').val();
            $.post('findChildren',{"category_id":categoryID},function(childrenInfo){
                if(childrenInfo.length > 0){
                    var optionHtml = "<option>==子类==</option>";
                    $(childrenInfo).each(function(){
                        optionHtml += "<option value="+this._id+">"+this.title+"</option>";
                    });

                    var selectHtml = "<select class='select3 tag-input-style' name='category[_parent_id]' id='category_parent_id' onchange='parentCategory()'>"
                            +optionHtml+"</select>";
                    $("#select-parent-category").append(selectHtml);
                }
            });

        }

        function parentCategory(){
            var select1Val = $('.select1').children('option').val();
            var select2Val = $('.select2').children('option:checked').val();
            var select3Val = $('.select3').children('option:checked').val();

            var parentID;

            if(select1Val != '' && select1Val != undefined){
                parentID = select1Val;
            }

            if(select2Val != '' && select2Val != undefined && select2Val != "==根类=="){
                parentID = select2Val;
            }

            if(select3Val != '' && select3Val != undefined && select3Val != "==子类=="){
                parentID = select3Val;
            }

            if(parentID == '' || parentID == undefined){
                parentID = $('#rootID').val();
            }

            $('#category_parent_id').val(parentID);
        }

</script>

app/views/categories/edit.html.erb
<%- model_class = Category -%>

<div class="col-sm-6">
  <div class="widget-box widget-color-blue2">
    <div class="widget-header">
      <h4 class="widget-title lighter smaller">修改商品类别</h4>
    </div>

    <div class="widget-body">
      <div class="widget-main padding-8">


        <%= render 'form' %>

      </div>
    </div>
  </div>
</div>

app/views/categories/index.html.erb
<%- model_class = Category -%>
<div class="page-header">
  <h1><%= model_class.model_name.human %>（总共<%= @categories.total_count %>条）</h1>
</div>

<div class="dataTables_wrapper form-inline no-footer">
  <div class="row">
    <div class="col-xs-6">
      <div class="dataTables_info" id="dynamic-table_info" role="status" aria-live="polite">
        <%= page_entries_info @categories %></div>
    </div>
    <div class="col-xs-6">
      <div class="dataTables_paginate paging_simple_numbers" id="dynamic-table_paginate">
        <ul class="pagination">
          <li class="paginate_button previous disabled" aria-controls="dynamic-table" tabindex="0" id="dynamic-table_previous">
            <%= paginate @categories %>
          </li>
        </ul>
      </div>
    </div>
  </div>

  <br>
  <%= form_tag categories_path, method: 'get' do %>
    标题<%= text_field_tag(:title)%>
      <%= submit_tag('搜索')%>
  <% end %>
  <br>

  <table class="table table-striped table-bordered table-hover">
    <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:form) %></th>
      <th><%= t '.actions', :default => t("helpers.actions") %></th>
    </tr>
    </thead>
    <tbody>
    <% @categories.each do |category| %>
        <tr>
          <td><%= link_to category.title, category_path(category) %></td>
          <td><%= category.form %></td>
          <td>
            <div class="hidden-sm hidden-xs action-buttons">
              <a class="btn btn-xs btn-info" href="<%= edit_category_path(category) %>">
                <i class="ace-icon fa fa-pencil bigger-130"></i>
              </a>
              <%= link_to raw("<i class='ace-icon fa fa-trash-o bigger-130'></i>"),
                          category_path(category),
                          :method => :delete,
                          :data => {:confirm => '你确定删除该商品吗?'},
                          :class => 'btn btn-xs btn-danger' %>
              <a class="btn btn-xs btn-info" href="<%= category_achieve_path(category) %>">
                <i class="ace-icon fa fa-check bigger-130"></i>
              </a>
            </div>
          </td>
        </tr>
    <% end %>

    </tbody>
  </table>

  <div class="row">
    <div class="col-xs-6">
      <div class="dataTables_info" id="dynamic-table_info" role="status" aria-live="polite">
        <%= page_entries_info @categories %></div>
    </div>
    <div class="col-xs-6">
      <div class="dataTables_paginate paging_simple_numbers" id="dynamic-table_paginate">
        <ul class="pagination">
          <li class="paginate_button previous disabled" aria-controls="dynamic-table" tabindex="0" id="dynamic-table_previous">
            <%= paginate @categories %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_category_path,
            :class => 'btn btn-primary' %>

<%= link_to '同步所有类别',
            category_achieve_path(:all),
            :class => 'btn btn-primary' %>

<script type="text/javascript">
    $(document).ready(function () {
        categories();
    });
</script>

app/views/categories/new.html.erb
<%- model_class = Category -%>

<div class="col-sm-6">
  <div class="widget-box widget-color-blue2">
    <div class="widget-header">
      <h4 class="widget-title lighter smaller">新建类别</h4>
    </div>

    <div class="widget-body">
      <div class="widget-main padding-8">


      <%= render 'form' %>

      </div>
    </div>
  </div>
</div>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @category.title %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @category.desc %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/categories/tree.html.erb
<div class="col-sm-12">
<%= link_to '新建', new_category_path, :class=>'btn btn-lg btn-success' %>
<%= link_to '编辑', "/categories", id: 'edit', :class=>'btn btn-lg btn-warn', method: :get %>
<%= link_to '删除', "/categories", id: 'delete', :class=>'btn btn-lg btn-warn', method: :delete, data: { confirm: 'Are you sure?' } %>
</div>

<br>


<div class="col-sm-6">
<div class="widget-box widget-color-blue2">
  <div class="widget-header">
    <h4 class="widget-title lighter smaller">类别列表</h4>
  </div>

  <div class="widget-body">
    <div class="widget-main padding-8">
      <ul id="treeview" class="tree"></ul>
    </div>
  </div>
</div>
</div>






<script type="text/javascript">
    $(function() {
        //construct the data source object to be used by tree
        var remoteUrl = '/categories/';

        var remoteDateSource = function(options, callback) {
            var parent_id = null
            if( !('text' in options || 'type' in options) ){
                parent_id = '0';//load first level data
            }
            else if('type' in options && options['type'] == 'folder') {//it has children
                if ('additionalParameters' in options) {
                    parent_id = options.additionalParameters[0].id
                }
            }

            if(parent_id !== null) {
                $.ajax({
                    url: remoteUrl + parent_id,
                    type: 'GET',
                    dataType: 'json',
                    success : function(response) {
                        callback({ data: response.data })
                    },
                    error: function(response) {
                        //console.log(response);
                    }
                })
            }
        }

        $('#treeview').ace_tree({
            dataSource: remoteDateSource ,
            loadingHTML: '<div class="tree-loading"><i class="ace-icon fa fa-refresh fa-spin blue"></i></div>',
            'open-icon' : 'ace-icon tree-minus',
            'close-icon' : 'ace-icon tree-plus',
            'selectable' : true,
            'folderSelect' : true,
            multiSelect: false,
            'selected-icon' : 'ace-icon fa fa-check',
            'unselected-icon' : 'ace-icon fa fa-times',
            cacheItems: true
        });

        $('#treeview').on('selected.fu.tree', function (event, data) {
           $('#delete').attr("href", "/categories/" + data.selected[0].id)
           $('#edit').attr("href", "/categories/" + data.selected[0].id + "/edit")
        })

    });
</script>